"""Stage 06 logic: apply min_score threshold and persist postfilter drops.

v13.0.0 changes (E.7):
  - run() now writes postfilter_debug.json alongside the existing
    postfilter_dropped_commits.json.  It contains an aggregated summary
    (total/kept/dropped, threshold, score distribution buckets) analogous
    to prefilter_debug.json, giving the user a fast overview of why commits
    were dropped at this stage without having to inspect the full JSON list.
  - CACHE_FILES['postfilter_debug'] key added to lib/manifest.py.
  - Convert f-strings to %%-format for Python 3.6 compatibility.

v18.0.1 fix (Fix 5):
  - Top score bucket label renamed '100+' -> '>=100' to match uncapped score
    semantics introduced in v16.5.0.

v19.0.0 (G):
  - Use batch_can_cherry_pick_cached() for SQLite-based caching
  - Incremental updates: only test new commits, reuse cached results
  - Per-target storage: one DB per rev_old
  - Progress bar with ETA during cherry-pick testing
"""
import os
import sys
from lib.config import load_json, save_json
from lib.manifest import CACHE_FILES, NSTAGES
from lib.pipeline_runtime import update_stage_progress
from lib.gitutils import batch_count_hunks, batch_can_cherry_pick_cached
from lib.backport import enrich_commit_backport


def _get_threshold(cfg):
    """Return the min_score threshold from filter.min_score (default 0)."""
    filt = cfg.get('filter', {}) or {}
    raw = filt.get('min_score', 0)
    try:
        return float(raw or 0)
    except (TypeError, ValueError):
        return 0.0


def _score_buckets(commits):
    """Return a dict mapping score-range labels to commit counts.

    Buckets: 0, 1-9, 10-19, 20-29, 30-49, 50-74, 75-99, >=100
    """
    buckets = {
        '0':     0,
        '1-9':   0,
        '10-19': 0,
        '20-29': 0,
        '30-49': 0,
        '50-74': 0,
        '75-99': 0,
        '>=100': 0,
    }
    for c in commits:
        s = int(c.get('score', 0) or 0)
        if s == 0:
            buckets['0'] += 1
        elif s < 10:
            buckets['1-9'] += 1
        elif s < 20:
            buckets['10-19'] += 1
        elif s < 30:
            buckets['20-29'] += 1
        elif s < 50:
            buckets['30-49'] += 1
        elif s < 75:
            buckets['50-74'] += 1
        elif s < 100:
            buckets['75-99'] += 1
        else:
            buckets['>=100'] += 1
    return buckets


def _generate_cherry_pick_check_script(output_dir, kernel_source_dir, target_rev, commits):
    """Generate a standalone Python script to re-run cherry-pick checks.
    
    The script can be run manually to verify cherry-pick status for each commit.
    It supports --verbose mode to dump all git commands.
    
    IMPORTANT: The generated script's can_cherry_pick() function must be kept
    in sync with lib/gitutils.py can_cherry_pick() to ensure consistent results.
    Any changes to conflict detection logic, output parsing, or error handling
    in lib/gitutils.py should be reflected in the generated script template.
    
    Args:
        output_dir: Directory to write the script to
        kernel_source_dir: Path to kernel git repository
        target_rev: Target revision to cherry-pick onto (e.g., kernel.rev_old)
        commits: List of relevant commits with cherry_pick_info
    """
    script_path = os.path.join(output_dir, 'cherry_pick_check.py')
    
    # Extract just the commit SHAs
    commit_shas = [c.get('commit', '') for c in commits if c.get('commit')]
    
    script_content = '''#!/usr/bin/env python3
"""Standalone cherry-pick feasibility checker.

This script was auto-generated by the kcommit-analysis-pipeline stage 06.
It re-runs cherry-pick tests for relevant commits onto {target_rev}.

Usage:
  python3 cherry_pick_check.py              # Normal mode
  python3 cherry_pick_check.py --verbose    # Verbose mode (dump git commands)
  python3 cherry_pick_check.py --json       # JSON output
  python3 cherry_pick_check.py --refresh    # Refresh SQLite database

The script uses `git show | git apply --check` to test feasibility.
This is much faster than cherry-pick because it doesn't modify the working tree.
"""
import argparse
import json
import os
import sqlite3
import subprocess
import sys
from datetime import datetime, timezone

KERNEL_SOURCE = {kernel_source!r}
TARGET_REV = {target_rev!r}
COMMITS = {commit_shas!r}

# SQLite database path (same as lib/cherrypick_db.py)
DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'cache', TARGET_REV, 'cherry.db')


def run_git(args, verbose=False):
    """Run a git command in the kernel source directory."""
    cmd = ['git', '-C', KERNEL_SOURCE] + args
    if verbose:
        print('  $', ' '.join(cmd), file=sys.stderr)
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    return result.stdout, result.stderr, result.returncode


def can_cherry_pick(sha, verbose=False):
    """Test if a commit can be cherry-picked cleanly onto current HEAD.
    
    Uses `git show | git apply --check` which tests if the patch applies
    without modifying the working tree. This matches lib/gitutils.py
    can_cherry_pick().
    
    IMPORTANT: This function must be kept in sync with lib/gitutils.py
    can_cherry_pick(). Any changes to:
      - Patch application logic (using git apply --check)
      - Conflict detection logic (checking error output)
      - Output parsing (extracting filenames from error messages)
      - Error handling and return format
    must be reflected in both places to ensure consistent results.
    
    Returns:
        dict with 'ok', 'conflicts', and 'error' keys
    """
    try:
        # Step 1: Get the patch for this commit
        if verbose:
            print('  Getting patch for %s...' % sha, file=sys.stderr)
        patch_out, patch_err, patch_rc = run_git(['show', '--no-renames', sha], verbose)
        patch = patch_out
        
        if not patch.strip():
            # Empty commit - always "applies"
            return {{'ok': True, 'conflicts': [], 'error': None}}
        
        # Step 2: Test if patch applies cleanly at target revision
        # CRITICAL: Pass patch to stdin (matches lib/gitutils.py)
        if verbose:
            print('  Testing if patch applies...', file=sys.stderr)
        cmd = ['git', '-C', KERNEL_SOURCE, 'apply', '--check', '--3way', '--unidiff-zero']
        result = subprocess.run(cmd, input=patch, capture_output=True, text=True, check=False)
        out, err, rc = result.stdout, result.stderr, result.returncode
        
        # Check return code: 0 = success, non-zero = conflict
        if rc == 0:
            return {{'ok': True, 'conflicts': [], 'error': None}}
        
        # Parse conflicted files from error output
        conflicts = []
        error_output = err if err else out
        for line in error_output.splitlines():
            # Lines like "error: file.c: does not match index"
            if 'error:' in line.lower() or 'does not match' in line.lower():
                # Extract filename
                if ':' in line:
                    parts = line.split(':')
                    # Look for a part that looks like a file path
                    for part in parts:
                        part = part.strip()
                        if '/' in part or part.endswith(('.c', '.h', '.S', '.make', '.mk')):
                            # This looks like a file path
                            fname = part.split()[0] if part else ''
                            if fname and fname not in conflicts:
                                conflicts.append(fname)
        return {{'ok': False, 'conflicts': conflicts, 'error': None}}
        
    except Exception as exc:
        if verbose:
            print('  Error: %s' % exc, file=sys.stderr)
        return {{'ok': False, 'conflicts': [], 'error': str(exc)}}


def load_cached_results():
    """Load cached cherry-pick results from SQLite database."""
    if not os.path.exists(DB_PATH):
        return {{}}
    
    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute('SELECT sha, ok, conflicts, error FROM commits')
        
        results = {{}}
        for row in cursor.fetchall():
            results[row['sha']] = {{
                'ok': bool(row['ok']),
                'conflicts': json.loads(row['conflicts']),
                'error': row['error'],
            }}
        conn.close()
        return results
    except Exception as exc:
        print('Warning: could not load cache (%s); re-testing all' % exc, file=sys.stderr)
        return {{}}


def save_results_to_cache(results):
    """Save cherry-pick results to SQLite database."""
    try:
        os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Create table if not exists
        cursor.execute(
            'CREATE TABLE IF NOT EXISTS commits ('
            'sha TEXT PRIMARY KEY, '
            'ok INTEGER NOT NULL, '
            'conflicts TEXT NOT NULL, '
            'error TEXT, '
            'tested_at TEXT NOT NULL)'
        )
        
        # Insert or replace results
        tested_at = datetime.now(timezone.utc).isoformat()
        for sha, result in results.items():
            conflicts_json = json.dumps(result.get('conflicts', []))
            cursor.execute(
                'INSERT OR REPLACE INTO commits '
                '(sha, ok, conflicts, error, tested_at) '
                'VALUES (?, ?, ?, ?, ?)',
                (sha, 1 if result.get('ok', False) else 0,
                 conflicts_json, result.get('error'), tested_at)
            )
        
        conn.commit()
        conn.close()
        print('  Saved %d results to %s' % (len(results), DB_PATH), file=sys.stderr)
    except Exception as exc:
        print('Warning: could not save cache (%s)' % exc, file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description='Re-run cherry-pick feasibility checks for relevant commits.')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Print all git commands')
    parser.add_argument('--json', action='store_true',
                        help='Output results as JSON')
    parser.add_argument('--refresh', action='store_true',
                        help='Re-test all commits and refresh SQLite database')
    args = parser.parse_args()
    
    if not os.path.isdir(KERNEL_SOURCE):
        print('Error: Kernel source directory not found: %s' % KERNEL_SOURCE,
              file=sys.stderr)
        sys.exit(1)
    
    if args.verbose:
        print('Kernel source: %s' % KERNEL_SOURCE, file=sys.stderr)
        print('Target revision: %s' % TARGET_REV, file=sys.stderr)
        print('Database: %s' % DB_PATH, file=sys.stderr)
    
    # Load cached results (unless --refresh)
    cached = {{}} if args.refresh else load_cached_results()
    if args.verbose and cached:
        print('Loaded %d cached results' % len(cached), file=sys.stderr)
    
    # Save current HEAD to restore later
    if args.verbose:
        print('  Saving current HEAD...', file=sys.stderr)
    out, err, rc = run_git(['rev-parse', 'HEAD'], args.verbose)
    current_head = out.strip() if rc == 0 else None
    
    try:
        # Checkout target revision ONCE (detached HEAD)
        if args.verbose:
            print('  Checking out %s...' % TARGET_REV, file=sys.stderr)
        out, err, rc = run_git(['checkout', '--force', '--detach', TARGET_REV], args.verbose)
        if rc != 0 and args.verbose:
            print('  Warning: checkout returned %d: %s' % (rc, err), file=sys.stderr)
        
        print('Checking %d commits for cherry-pick feasibility onto %s...' % (
            len(COMMITS), TARGET_REV))
        
        results = []
        ok_count = 0
        fail_count = 0
        new_results = {{}}  # For caching
        
        for i, sha in enumerate(COMMITS, 1):
            if args.verbose:
                print('\\n[%d/%d] %s' % (i, len(COMMITS), sha[:12]), file=sys.stderr)
            
            # Check cache first (unless --refresh)
            if not args.refresh and sha in cached:
                result = cached[sha].copy()
                result['sha'] = sha
                result['cached'] = True
                results.append(result)
                if args.verbose:
                    print('  [cached] %s' % ('clean' if result['ok'] else 'conflict'), file=sys.stderr)
            else:
                # Test this commit
                result = can_cherry_pick(sha, verbose=args.verbose)
                result['sha'] = sha
                result['cached'] = False
                results.append(result)
                new_results[sha] = result
            
            if result['ok']:
                ok_count += 1
                status = '✓ clean' + (' [cached]' if result.get('cached') else '')
            else:
                fail_count += 1
                status = '✗ conflict' + (' (%d files)' % len(result['conflicts'])
                                         if result['conflicts'] else '')
            
            if not args.json:
                print('[%d/%d] %s: %s' % (i, len(COMMITS), sha[:12], status))
                if result['conflicts'] and not args.verbose:
                    for f in result['conflicts'][:5]:
                        print('    - %s' % f)
                    if len(result['conflicts']) > 5:
                        print('    ... and %d more' % (len(result['conflicts']) - 5))
        
        # Save new results to cache
        if new_results:
            save_results_to_cache(new_results)
        
        if args.json:
            print(json.dumps({{
                'summary': {{
                    'total': len(COMMITS),
                    'clean': ok_count,
                    'conflicts': fail_count,
                    'target_rev': TARGET_REV,
                    'kernel_source': KERNEL_SOURCE,
                    'cached': len([r for r in results if r.get('cached')]),
                    'tested': len(new_results),
                }},
                'results': results,
            }}, indent=2))
        else:
            print('\\nSummary: %d/%d clean, %d with conflicts' % (
                ok_count, len(COMMITS), fail_count))
            if new_results:
                print('  Tested %d new commits, reused %d cached' % (
                    len(new_results), len(cached)))
    
    finally:
        # Always restore original HEAD
        if current_head:
            if args.verbose:
                print('\\n  Restoring HEAD to %s...' % current_head, file=sys.stderr)
            run_git(['checkout', '--force', '--detach', current_head], args.verbose)


if __name__ == '__main__':
    main()
'''.format(
        target_rev=target_rev,
        kernel_source=kernel_source_dir,
        commit_shas=commit_shas,
    )
    
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(script_content)
    
    # Make executable
    os.chmod(script_path, 0o755)
    
    print('  Generated: %s' % script_path)


def _enrich_backport(cfg, relevant):
    """Attach backport indicators (and optional hunk counts) to relevant commits.

    Runs *after* filtering, over the small relevant set only, so the optional
    patch-inspection pass for hunk counting never touches the full commit
    range (perf).  Hunk counting is opt-in via collect.count_hunks; when off,
    stats['hunks'] stays 0 and the hunks term contributes nothing to
    backport_complexity.

    Cherry-pick test is opt-in via collect.cherry_pick_test; when enabled,
    each relevant commit is tested for clean cherry-pick onto kernel.rev_old
    and the result is stored as cherry_pickable (bool) plus optional details
    in cherry_pick_info.

    Order of operations:
      1. (optional) count hunks per commit via a single batched git show.
      2. (optional) test cherry-pick feasibility via batched git cherry-pick.
      3. compute score_norm / backport_complexity / pick_priority, using the
         run-relative max score for score normalization.
    """
    if not relevant:
        return relevant

    collect = cfg.get('collect', {}) or {}
    kernel = cfg.get('kernel', {}) or {}
    
    # 1. Optional hunk counting
    if collect.get('count_hunks'):
        shas = [c.get('commit') for c in relevant if c.get('commit')]
        try:
            counts = batch_count_hunks(cfg, shas)
        except Exception as exc:   # git access is best-effort; never crash stage 06
            print('  warning: hunk counting failed (%s); hunks set to 0' % exc)
            counts = {}
        for c in relevant:
            stats = c.get('stats')
            if not isinstance(stats, dict):
                stats = {}
                c['stats'] = stats
            stats['hunks'] = int(counts.get(c.get('commit'), 0) or 0)
    
    # 2. Optional cherry-pick test (with SQLite caching and progress bar)
    if collect.get('cherry_pick_test') and kernel.get('rev_old'):
        shas = [c.get('commit') for c in relevant if c.get('commit')]
        target_rev = kernel['rev_old']
        
        # Progress callback for cherry-pick test using standard mechanism
        total = len(shas)
        step = max(1, total // 80)
        
        def _progress(done, total, eta_seconds=None):
            """Update stage progress (eta_seconds is ignored for pipeline progress)."""
            if done % step == 0 or done == total:
                update_stage_progress(6, NSTAGES, done / max(total, 1),
                                      'cherry-pick test', n_done=done, n_total=total)
        
        try:
            # Use cached version - only tests new commits, shows progress bar with ETA
            cp_results = batch_can_cherry_pick_cached(cfg, shas, target_rev, progress_callback=_progress)
        except Exception as exc:
            print('  warning: cherry-pick test failed (%s); skipping' % exc)
            cp_results = {}
        
        ok_count = sum(1 for r in cp_results.values() if r.get('ok'))
        fail_count = len(cp_results) - ok_count
        print('  cherry-pick: %d/%d clean, %d with conflicts' % (
            ok_count, len(cp_results), fail_count))
        
        for c in relevant:
            sha = c.get('commit', '')
            if sha in cp_results:
                result = cp_results[sha]
                c['cherry_pickable'] = result.get('ok', False)
                # Store full result for inspection if needed
                c['cherry_pick_info'] = {
                    'ok': result.get('ok', False),
                    'conflicts': result.get('conflicts', []),
                    'error': result.get('error'),
                }
            else:
                # Commit not in results (e.g., missing SHA)
                c['cherry_pickable'] = None
                c['cherry_pick_info'] = None

    max_score = max((int(c.get('score', 0) or 0) for c in relevant), default=0)
    for c in relevant:
        enrich_commit_backport(c, max_score)
    return relevant


def run(cfg, cache):
    """Sort, threshold-filter, rank commits and write output caches.

    Returns (relevant, low_score, threshold).

    Outputs written:
      CACHE_FILES['relevant']           -- kept commits with _rank assigned
      CACHE_FILES['postfilter_dropped'] -- commits below threshold
      CACHE_FILES['postfilter_debug']   -- aggregated summary (E.7)
    """
    scored = load_json(os.path.join(cache, CACHE_FILES['scored']), default=[]) or []

    threshold = _get_threshold(cfg)
    if threshold > 0:
        relevant  = [c for c in scored if (c.get('score', 0) or 0) >= threshold]
        low_score = [c for c in scored if (c.get('score', 0) or 0) <  threshold]
        print('  threshold %s: kept %d/%d, dropped %d' % (
            threshold, len(relevant), len(scored), len(low_score)))
    else:
        relevant  = scored
        low_score = []
        print('  no threshold (min_score=0): keeping all %d commits' % len(relevant))

    # Enrich with backport indicators (including pick_priority) before sorting
    # and ranking, so we can sort by pick_priority on the Python side.
    _enrich_backport(cfg, relevant)

    # Sort by pick_priority descending, then score descending, then
    # backport_complexity ascending (lower = easier to backport).
    # Using a tuple key for multi-level sorting as tie-breakers.
    relevant = sorted(
        relevant,
        key=lambda c: (
            -(c.get('pick_priority', 0) or 0),   # descending: negate for ascending sort
            -(c.get('score', 0) or 0),             # descending
            c.get('backport_complexity', 0) or 0,  # ascending: lower complexity first
        )
    )

    for rank, c in enumerate(relevant, 1):
        c['_rank'] = rank

    save_json(os.path.join(cache, CACHE_FILES['relevant']), relevant)

    label = 'score_below_threshold (%s)' % threshold
    for c in low_score:
        c['_filter_reason'] = label
    save_json(os.path.join(cache, CACHE_FILES['postfilter_dropped']), low_score)

    # E.7: write postfilter_debug.json -- aggregated observability summary
    debug_output = {
        'summary': {
            'total_scored':      len(scored),
            'kept':              len(relevant),
            'dropped':           len(low_score),
            'threshold':         threshold,
            'top_score':         int((relevant[0].get('score', 0) or 0))  if relevant  else 0,
            'bottom_kept_score': int((relevant[-1].get('score', 0) or 0)) if relevant  else 0,
            'top_dropped_score': int((low_score[0].get('score', 0) or 0)) if low_score else 0,
        },
        'score_distribution': {
            'all_scored': _score_buckets(scored),
            'kept':       _score_buckets(relevant),
            'dropped':    _score_buckets(low_score),
        },
    }
    save_json(os.path.join(cache, CACHE_FILES['postfilter_debug']), debug_output)

    # Generate standalone cherry-pick check script if cherry-pick test was enabled
    collect = cfg.get('collect', {}) or {}
    kernel = cfg.get('kernel', {}) or {}
    if collect.get('cherry_pick_test') and kernel.get('rev_old'):
        # Output directory is sibling of cache directory (work/cache -> work/output)
        work_dir = os.path.dirname(cache)
        output_dir = os.path.join(work_dir, 'output')
        os.makedirs(output_dir, exist_ok=True)
        _generate_cherry_pick_check_script(
            output_dir=output_dir,
            kernel_source_dir=kernel.get('source_dir', ''),
            target_rev=kernel.get('rev_old', ''),
            commits=relevant,
        )

    return relevant, low_score, threshold
