"""cherrypick_script_gen.py -- kcommit-analysis-pipeline v19.4.1

Generates ready-to-run shell scripts that cherry-pick every commit already
confirmed cherry-pickable (CherryDB result ok=True) onto kernel.rev_old, in
strict git-history order (oldest -> newest).

Two scripts are generated by stage 07 (report_commits) when
collect.cherry_pick_test is enabled and kernel.rev_old is configured:

  cherry_pick_prefiltered.sh  -- from cache/prefilter_kept_commits.json
                                  (stage 04 output: every commit that passed
                                  the prefilter phase, regardless of score)
  cherry_pick_relevant.sh     -- from cache/relevant_commits.json
                                  (stage 06 output: the final, score-thresholded
                                  set)

Why not just reuse the JSON cache's own ordering
--------------------------------------------------
Neither cache file is guaranteed usable as-is for ordering purposes:
  - relevant_commits.json is rank-sorted by pick_priority/score/complexity
    (see lib/stages/st06_postfilter.py), NOT by git history.
  - prefilter_kept_commits.json happens to be written in git log --reverse
    order at collection time, but this module does not rely on that
    implicitly -- both scripts re-derive ordering the same explicit way.

So both scripts re-derive the authoritative oldest -> newest order by calling
lib.gitutils.list_rev_commits() (git rev-list --reverse rev_old..rev_new) and
filtering that master sequence down to the selected, cherry-pickable SHA set.
This guarantees correct application order regardless of how the source JSON
is sorted.

Cherry-pickability source of truth
-----------------------------------
lib.cherrypick_db.CherryDB, keyed by kernel.rev_old, under
collect.cherry_pick_cache_dir.  This database is filled either by a full
pipeline run (stage 05 -- see lib/stages/st05_score.py::_enrich_cherry_pick())
or by an on-demand `cp-check` run (lib/commands/cmd_cp_check.py).  Either way,
this module only ever reads it -- it never tests commits itself.

Only SHAs with a cached result of ok=True are included in the generated
script.  SHAs that are untested or conflict (ok=False) are omitted from the
script body but counted in the header comment and returned stats, so
staleness (commits added since the last cp-check/pipeline run) is visible
rather than silently hidden.

v19.4.1:
  - Fixed O(N^2) file I/O bug: build_cherry_pick_script() previously called
    a helper that re-opened and linearly re-scanned the whole commit-set
    JSON file once *per commit* just to look up its subject line for the
    inline script comment.  For large commit sets (thousands of commits in
    prefilter_kept_commits.json) this degenerated into hundreds of
    thousands of redundant open/read/close cycles on the same file --
    visible under strace as what looked like an infinite open/close loop,
    and slow enough in practice to appear hung.  The commit list is now
    loaded once per script and indexed into a sha -> subject dict before
    the per-commit loop, so lookup is O(1) and the file is read exactly
    once.
"""
import os
import stat
import datetime

from lib.config import load_json
from lib.manifest import CACHE_FILES, VERSION
from lib.cherrypick_db import get_cherry_db_path, load_or_create_db
from lib.gitutils import list_rev_commits


def _now_iso():
    try:
        return datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    except AttributeError:
        return datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')


def _load_commits(cache, cache_key):
    """Return the raw commit dict list for *cache_key*, read once from disk."""
    return load_json(os.path.join(cache, CACHE_FILES[cache_key]), default=[]) or []


def _index_shas_and_subjects(commits):
    """Build (ordered deduped sha list, sha -> subject dict) in a single pass.

    v19.4.1: replaces the old per-SHA _load_commit_shas()/_subject_for()
    pair, which each re-read the whole JSON file from disk.  This function
    is called exactly once per generated script, on the already-loaded
    commit list, so total file I/O is O(1) regardless of commit-set size.
    """
    seen = set()
    shas = []
    subjects = {}
    for c in commits:
        if not isinstance(c, dict):
            continue
        sha = c.get('commit')
        if not sha:
            continue
        if sha not in seen:
            seen.add(sha)
            shas.append(sha)
            subjects[sha] = (c.get('subject') or '').replace('\n', ' ').strip()
    return shas, subjects


def build_cherry_pick_script(cfg, cache, cache_key):
    """Build the cherry-pick script text and stats for one commit set.

    Args:
        cfg:       pipeline config dict
        cache:     absolute path to the pipeline cache directory
        cache_key: one of 'prefilter_kept' or 'relevant' (lib.manifest.CACHE_FILES key)

    Returns:
        (script_text, stats) where stats is a dict with:
          total_in_set, tested, cherry_pickable, skipped_untested, skipped_conflict
        Returns (None, stats) when nothing is available to write (e.g. no
        commits in the set, or the CherryDB is missing/empty) -- callers
        should skip writing the file in that case, stats still reflect why.
    """
    kernel  = cfg.get('kernel', {}) or {}
    collect = cfg.get('collect', {}) or {}

    target_rev = kernel.get('rev_old')
    rev_new    = kernel.get('rev_new')
    cache_dir  = collect.get('cherry_pick_cache_dir')

    # v19.4.1: read the commit-set JSON exactly once; both the SHA list and
    # the subject lookup table are derived from this single in-memory copy.
    commits = _load_commits(cache, cache_key)
    shas, subjects = _index_shas_and_subjects(commits)

    stats = {
        'total_in_set':     len(shas),
        'tested':            0,
        'cherry_pickable':   0,
        'skipped_untested':  0,
        'skipped_conflict':  0,
    }

    if not shas or not target_rev or not cache_dir:
        stats['skipped_untested'] = len(shas)
        return None, stats

    db_path = get_cherry_db_path(cache_dir, target_rev)
    if not os.path.exists(db_path):
        stats['skipped_untested'] = len(shas)
        return None, stats

    db = load_or_create_db(cache_dir, target_rev)
    try:
        results = db.get_results(shas)
    finally:
        db.save()

    ok_shas = set()
    for sha in shas:
        result = results.get(sha)
        if result is None:
            stats['skipped_untested'] += 1
            continue
        stats['tested'] += 1
        if result.get('ok'):
            ok_shas.add(sha)
        else:
            stats['skipped_conflict'] += 1
    stats['cherry_pickable'] = len(ok_shas)

    if not ok_shas:
        return None, stats

    # Re-derive authoritative oldest -> newest order from git history itself,
    # never from the JSON cache's own (possibly score-ranked) ordering.
    try:
        history_order = list_rev_commits(cfg)
    except Exception:
        history_order = shas  # best-effort fallback; still filtered below

    ordered = [sha for sha in history_order if sha in ok_shas]
    # Safety net: include any ok_shas that history_order might have missed
    # (e.g. merge commits excluded by collect.no_merges) at the end, in the
    # cache's own relative order, so no cherry-pickable commit is silently lost.
    missing = [sha for sha in shas if sha in ok_shas and sha not in ordered]
    ordered.extend(missing)

    lines = [
        '#!/usr/bin/env bash',
        '# Auto-generated by kcommit-analysis-pipeline %s' % VERSION,
        '# Generated at: %s' % _now_iso(),
        '# Commit set:   %s' % cache_key,
        '# Target rev:   %s' % target_rev,
        '# Source range: %s..%s' % (target_rev, rev_new or '?'),
        '#',
        '# %d commit(s) in set, %d tested, %d cherry-pickable (ok=True),'
        % (stats['total_in_set'], stats['tested'], stats['cherry_pickable']),
        '# %d untested (run cp-check to test them), %d with conflicts (skipped).'
        % (stats['skipped_untested'], stats['skipped_conflict']),
        '#',
        '# Commits are applied in git-history order (oldest first), independent',
        '# of any score/rank ordering used elsewhere in the pipeline reports.',
        '#',
        '# On conflict, git cherry-pick stops; resolve then run:',
        '#   git cherry-pick --continue',
        '# or abort the whole sequence with:',
        '#   git cherry-pick --abort',
        '',
        'set -euo pipefail',
        '',
    ]
    for sha in ordered:
        subject = subjects.get(sha, '')
        comment = ('  # %s' % subject) if subject else ''
        lines.append('git cherry-pick %s%s' % (sha, comment))
    lines.append('')

    return '\n'.join(lines), stats


def write_cherry_pick_script(cfg, cache, outdir, cache_key, filename):
    """Build and write one cherry-pick script to *outdir*/*filename*.

    Returns (path_or_none, stats).  path_or_none is None when there was
    nothing cherry-pickable to write (see build_cherry_pick_script()); the
    caller should not add it to generated_files in that case.
    """
    script_text, stats = build_cherry_pick_script(cfg, cache, cache_key)
    if script_text is None:
        return None, stats

    path = os.path.join(outdir, filename)
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(script_text)

    try:
        st = os.stat(path)
        os.chmod(path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP)
    except OSError:
        pass

    return path, stats
